### ISSUE TITLE
Lyrics align

### ISSUE THREAD

**Issue by zetako** [poly000/waylyrics#45]
Somebody like me usually put the lirics at border of the screen. A align option in config file will be useful. 

Also, I already try modify css theme file with `test-align: right`, but it seems not working. I'm not familiar with rust and cannot figure out how css be turn into lyric windows. Any suggestions?

I'm using Manjaro + KDE on X11, and the modified css file is as below:
```css
window {
    background-color: rgba(0, 0, 0, 0.0);
}

label {
    /* 圆角 */
    border-radius: 16px;

    font-size: 28px;
    color: rgba(255, 255, 255, 1.0);
    background-color: rgba(0, 0, 0, 0.3);
    padding: 10px;

    text-align: right !important;
}

/* 相比于label的变更, 改为 label#origin 则为应用到原歌词 */
label#translated {
    border-radius: 12px;
    margin: 5px 0px;
    font-size: 24px;
    padding: 7px;
}
```
